version: "3"

services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  prisma-mysql-api:
    depends_on:
      - mysqldb
    build: .
    ports:
      - 3300:3300
    environment:
      - DATABASE_URL=mysql://root:root@mysqldb:3306/railway
